### ISSUE TITLE
Support percentage mode

### ISSUE THREAD

**Issue by zouhangwithsweet** [xsjcTony/unocss-preset-animations#3]
### Clear and concise description of the problem

For now, the preset doesnot support. I have to change it to `48/100`
`slide-out-to-top-[48%]`

### Suggested solution

animate-name-xxx-[xx%]

### Validations

- [X] Read the [documentation](https://unocss-preset-animations.aelita.me/) of using the package
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate

**Comment by xsjcTony** [comment]
Thanks for the report.
The `[]` syntax is removed intentionally, you can view the reason here: https://unocss-preset-animations.aelita.me/animations/
I'll try to look into whether I can add support for `%` syntax, e.g. `slide-out-to-top-48%` when I get some time.

**Comment by xsjcTony** [comment]
I've had a look at my implementation, it already supports percentage format, just without the bracket.
[Playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIEDswFsEAuApgLQD2ArgVEnGCKZQSQWS2QA4kAsAHAKRRseQqRAUAToTBksJAEwAGZUJz5iJAEZkCAC1UiNDRAE8SARmWL0APgAyZMgGsh1XEWAB6cBBtA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRwjx8iBLezsbwXJjWHqDBoeFRMZRxkMhOBiiYWZw5sB6JgsSiqbJymBbQbfKKKmqw6gAUko4%2BAgBcoADaOmMZ-pRDAJRe81VGtfUeK14AukHLgkA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA)
But that's indeed a missing test case, thanks for reporting anyway.

**Comment by xsjcTony** [comment]
I've updated the documentation, feel free to raise a new issue if you need something else.
