### ISSUE TITLE
Bracket syntax not registering

### ISSUE THREAD

**Issue by saturnonearth** [xsjcTony/unocss-preset-animations#7]
### unocss-preset-animations version

1.1.0

### Describe the bug

It does not seem to be picking up this type of syntax `slide-out-to-top-[48%]`, but `slide-out-to-top-48%` works. Is it possible to make the bracket version work?

### Reproduction

[Using `slide-out-to-top-[48%]` is not recognizable as a class.](https://unocss.dev/play/#html=DwEwlgbgBAxgNgQwM5ILwCIEDswFsEAuApgLRhZRJxgikD2ArgSQXS3QA4kAsAHAKToAfAHU6AJwDWSYAHpwEIQCgloSLEQoM2PIVLlK1WiUbNW7LgG0%2B-ALrCAInSJIoWOgSgB3CZLkKhIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUlCRYiOaOa5QAQ17S4GrTv2GIxugFoRCr4O9iBOwNJ6ANxISBgAHpbwmFgOXAA2Sdh4hMRkABTIqFDp9ABccADaVKgVehJcdDA6vsVpGHrk1lJp0OV6tGh6rgC6sqNUdAAW0DD1MHTlhaj69Y3NUzNzen0w8TC%2BaaRwu3H70MGkGHDTAG4YUKUn%2B7sOaR1UarIBjAuV1TYKZQQPIASlkwnkjCYITC0lB4IBUNY7G4vAE8P%2B3xgkjhS2WcDoEleGHKAEYAHQAJgRqAkaFwfUmrDACwA9Kz6CByVNWe98WowVRxgKkEA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA)

![CleanShot 2024-11-20 at 17 39 57@2x](https://github.com/user-attachments/assets/a5630e2a-5d5d-40fe-a87b-04f5d1a866ef)

Notice the underline is not there

### Validations

- [X] Check that there isn't [already an issue](https://github.com/xsjcTony/unocss-preset-animations/issues) that reports the same bug to avoid creating a duplicate
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/xsjcTony/unocss-preset-animations/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug

**Comment by xsjcTony** [comment]
Hi, there's a reason why it's not supported.
Please read the warning section here: https://unocss-preset-animations.aelita.me/animations/
